### ISSUE TITLE
Panic when trying to extract registry auth from a service without registry auth

### ISSUE THREAD

**Issue by matyasrichter** [crazy-max/swarm-cronjob#179]
#### Steps to reproduce this issue

1. Deploy a service without `--with-registry-auth`
2. Set `swarm.cronjob.registry-auth=true` for that service
3. Wait for swarm-cronjob to trigger that job

#### Expected behaviour

Not really sure, I think it would make sense to log a warning and try to run that service anyway.

#### Actual behaviour

swarm-cronjob (or rather, the docker cli package, if I understand correctly) panics

### Configuration

* Target Docker version (the host/cluster you manage) : 20.10.7
* Platform (windows/linux) : Linux Ubuntu 20.04.4 LTS

### Logs

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x220 pc=0x937d53]
goroutine 84 [running]:
github.com/docker/cli/cli/command.ElectAuthServer({0xbe2f50, 0xc00009c000}, {0xbf31b8, 0xc000074750})
	/go/pkg/mod/github.com/docker/cli@v20.10.8+incompatible/cli/command/registry.go:31 +0x73
github.com/docker/cli/cli/command.ResolveAuthConfig({0xbe2f50, 0xc00009c000}, {0xbf31b8, 0xc000074750}, 0x0)
	/go/pkg/mod/github.com/docker/cli@v20.10.8+incompatible/cli/command/registry.go:86 +0x9a
github.com/docker/cli/cli/command.resolveAuthConfigFromImage({0xbe2f50, 0xc00009c000}, {0xbf31b8, 0xc000074750}, {0xc000082f00, 0xc00032b150})
	/go/pkg/mod/github.com/docker/cli@v20.10.8+incompatible/cli/command/registry.go:213 +0x112
github.com/docker/cli/cli/command.RetrieveAuthTokenFromImage({0xbe2f50, 0xc00009c000}, {0xbf31b8, 0xc000074750}, {0xc000082f00, 0x0})
	/go/pkg/mod/github.com/docker/cli@v20.10.8+incompatible/cli/command/registry.go:192 +0x7b
github.com/crazy-max/swarm-cronjob/internal/docker.(*dockerClient).RetrieveAuthTokenFromImage(0xc00021aa20, {0xbe2f50, 0xc00009c000}, {0xc000082f00, 0x0})
	/src/internal/docker/client.go:65 +0x45
github.com/crazy-max/swarm-cronjob/internal/worker.(*Client).Run(0xc000477f40)
	/src/internal/worker/worker.go:72 +0x63e
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xb2
```

**Comment by crazy-max** [comment]
fixed by #202
